//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kalkulator_roboczogodzin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dodaj_zlecenie
    {
        public int Id { get; set; }
        public string Zleceniodawca { get; set; }
        public string NumerKatalogowy { get; set; }
        public string Nazwa { get; set; }
        public string Opis { get; set; }
        public string PrzewidywanyCzasPracy { get; set; }
        public string DataRealizacjiKlient { get; set; }
        public string DataRealizacjiFinalna { get; set; }
    }
}
